#for BSVTools
MAKEPATH := $(dir $(lastword $(MAKEFILE_LIST)))
MODULENAME := BlueFabric
MODULEPATH := $(MAKEPATH)src
EXTRA_BSV_LIBS += $(MODULEPATH)
EXTRA_BSV_LIBS += $(MODULEPATH)/ahb
EXTRA_BSV_LIBS += $(MODULEPATH)/axi
EXTRA_BSV_LIBS += $(MODULEPATH)/apb
EXTRA_BSV_LIBS += $(MODULEPATH)/axis
EXTRA_BSV_LIBS += $(MODULEPATH)/common
EXTRA_BSV_LIBS += $(MODULEPATH)/soc

$(info Adding $(MODULENAME) from $(MODULEPATH))